# Generated by Django 3.0.2 on 2020-01-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='own_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userorganizations',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('owner', 'owner'), ('admin', 'admin'), ('auditor', 'auditor'), ('reporter', 'reporter'), ('visitor', 'visitor')], default='visitor', max_length=12),
        ),
    ]
