# Generated by Django 3.0.2 on 2020-01-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200130_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
