# Generated by Django 3.0.2 on 2020-01-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20200130_1257'),
        ('core', '0001_auto_20200129_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='account.Organization'),
        ),
        migrations.AddField(
            model_name='provider',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='core.UserProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('owner', 'owner'), ('admin', 'admin'), ('auditor', 'auditor'), ('reporter', 'reporter'), ('visitor', 'visitor')], default='visitor', max_length=12),
        ),
    ]
