# Generated by Django 2.2.3 on 2019-08-25 14:12

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
    ]
